### ISSUE TITLE
Cannot log in using Microsoft Account (1.12)

### ISSUE THREAD

**Issue by DjingaNinja** [Sintinium/oauth#20]
Using my Microsoft Account to log in creates an error referring me to this link to create an issue. I tried to use my Mojang log in as well and it finds my character profile but then tells me that my password is wrong after I've already logged in
<img width="958" alt="Minecraft issue 1" src="https://user-images.githubusercontent.com/98440880/151097866-ebcab92c-2615-42f7-8761-c9197c217b1f.PNG">

**Comment by Sintinium** [comment]
So a couple of things:

I recommend updating to the newest version and seeing if the error changes. If it does send me the updated log.

I'm guessing you login normally through Microsoft? If so do you own Minecraft normally or do you own it through the GamePass?

**Comment by Danieljunek17** [comment]
Hey, I pretty much have the same problem! I have just today fresh installed the mod to address maybe it being an older version but it is not in my case but the first time it works normally opens the browser connects to my account and then Minecraft mod be like: I don't like this I will verify this forever

![image](https://user-images.githubusercontent.com/35172052/155343769-74e84924-0e83-4c89-8055-51c81b8d70d8.png)
```[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: java.net.BindException: Address already in use: bind
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/sun.nio.ch.Net.bind(Net.java:455)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/sun.nio.ch.Net.bind(Net.java:447)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:137)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at com.sintinium.oauth.login.MicrosoftLogin.authorizeUser(MicrosoftLogin.java:242)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:225)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:92)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:229)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.ErrorScreen:<init>:33]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: java.net.BindException: Address already in use: bind
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/sun.nio.ch.Net.bind0(Native Method)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/sun.nio.ch.Net.bind(Net.java:455)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/sun.nio.ch.Net.bind(Net.java:447)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:227)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/sun.nio.ch.ServerSocketAdaptor.bind(ServerSocketAdaptor.java:80)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at jdk.httpserver/sun.net.httpserver.ServerImpl.<init>(ServerImpl.java:101)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at jdk.httpserver/sun.net.httpserver.HttpServerImpl.<init>(HttpServerImpl.java:50)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at jdk.httpserver/sun.net.httpserver.DefaultHttpServerProvider.createHttpServer(DefaultHttpServerProvider.java:35)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at jdk.httpserver/com.sun.net.httpserver.HttpServer.create(HttpServer.java:137)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at com.sintinium.oauth.login.MicrosoftLogin.authorizeUser(MicrosoftLogin.java:242)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:225)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:92)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at com.sintinium.oauth.gui.profile.ProfileSelectionScreen.lambda$onMicrosoftType$10(ProfileSelectionScreen.java:229)
[15:51:32] [Oauth microsoft/INFO] [STDERR/]: [com.sintinium.oauth.gui.profile.ProfileSelectionScreen:lambda$onMicrosoftType$10:237]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[15:51:32] [Oauth microsoft/ERROR] [co.si.oa.gu.pr.ProfileSelectionScreen/]: ```


NOTE: this is when trying it the second time and I can't seem to find anything related to failing in the first place!

**Comment by Sintinium** [comment]
I believe this is now fixed. If not feel free to reopen. Thanks!

**Comment by Sintinium** [comment]
What Minecraft version is this? Could you give the log file?

**Comment by Sintinium** [comment]
Thanks! It looks like you're trying to log in using the old Mojang logins which Microsoft removed a few months ago. If you haven't already you'll need to migrate your account and log in using your Microsoft account. Unfortunately the 1.12 version is pretty old and I haven't removed the old login method.

**Comment by Sintinium** [comment]
Are you clicking on login with Microsoft in the mod?

**Comment by Sintinium** [comment]
Oh ok thanks. I'll see if I can find what the issue is
