### ISSUE TITLE
"An Error Occurred"

### ISSUE THREAD

**Issue by EvanHsieh0415** [Sintinium/oauth#22]
![](https://cdn.discordapp.com/attachments/906141481797042186/938383588288774174/unknown.png)

```
[18:40:52] [Netty Client IO #2/INFO] [FML]: Attempting connection with missing mods [betteradvancements, clienttweaks, colouredtooltips, controlling, ctgui, ctm, custommainmenu, defaultoptions, enchdesc, fbp, hurtanimationremover, loadingscreens, loliasm, mixinbooter, moreoverlays, mousetweaks, neat, oauth, pdp, resourceloader, rpmtw_update_mod, smoothfont, tipthescales, toastcontrol, worldbook, phosphor-lighting] at SERVER
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: java.lang.NullPointerException
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.login.LoginUtil.isOnline(LoginUtil.java:45)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.login.LoginUtil.updateOnlineStatus(LoginUtil.java:32)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.login.LoginUtil.setSession(LoginUtil.java:93)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.login.LoginUtil.loginMs(LoginUtil.java:60)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:94)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at com.sintinium.oauth.gui.LoginTypeScreen.lambda$null$2(LoginTypeScreen.java:32)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.LoginTypeScreen:lambda$null$2:37]: 	at java.lang.Thread.run(Thread.java:748)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: java.lang.NullPointerException
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.login.LoginUtil.isOnline(LoginUtil.java:45)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.login.LoginUtil.updateOnlineStatus(LoginUtil.java:32)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.login.LoginUtil.setSession(LoginUtil.java:93)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.login.LoginUtil.loginMs(LoginUtil.java:60)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:94)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at com.sintinium.oauth.gui.LoginTypeScreen.lambda$null$2(LoginTypeScreen.java:32)
[18:40:58] [Thread-313/INFO] [STDERR]: [com.sintinium.oauth.gui.ErrorScreen:<init>:27]: 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by Sintinium** [comment]
Which version are you on? 1.16 and 1.18's newest versions *should* fix this issue. If you're on 1.12 I might need to backport that fix

**Comment by EvanHsieh0415** [comment]
1.12.2

**Comment by Sintinium** [comment]
Ok I'll try to backport a fix when I have the time

**Comment by Sintinium** [comment]
Should be fixed in latest release
