### ISSUE TITLE
Incompatible with 1.18.2

### ISSUE THREAD

**Issue by Hubcapp** [Sintinium/oauth#26]
![image](https://user-images.githubusercontent.com/1337967/156309705-838e11ba-b492-467b-abda-36c47276e593.png)

Clicking the OAuth Login button on the multiplayer screen here will crash the game. The stack trace looks like it's reaching into the base 1.18.2 jar, and looking for a method that has been renamed between 1.18.1 and 1.18.2.

```
---- Minecraft Crash Report ----
// Don't do that.

Time: 3/2/22, 12:48 AM
Description: mouseClicked event handler

java.lang.NoSuchMethodError: 'net.minecraft.class_2874 net.minecraft.class_2874.method_32922(java.util.OptionalLong, boolean, boolean, boolean, boolean, double, boolean, boolean, boolean, boolean, boolean, int, int, int, net.minecraft.class_2960, net.minecraft.class_2960, float)'
	at com.sintinium.oauthfabric.gui.profile.FakeDimensionType.getInstance(FakeDimensionType.java:10)
	at com.sintinium.oauthfabric.gui.profile.FakeWorld.<init>(FakeWorld.java:21)
	at com.sintinium.oauthfabric.gui.profile.FakeWorld.getInstance(FakeWorld.java:15)
	at com.sintinium.oauthfabric.gui.profile.FakePlayer.<init>(FakePlayer.java:26)
	at com.sintinium.oauthfabric.gui.profile.FakePlayer.getInstance(FakePlayer.java:34)
	at com.sintinium.oauthfabric.gui.profile.ProfileSelectionScreen.method_25426(ProfileSelectionScreen.java:53)
	at net.minecraft.class_437.method_25423(class_437.java:389)
	at net.minecraft.class_310.method_1507(class_310.java:993)
```

This issue affects both the Forge & Fabric variants of this mod. I do not have any other mods installed.

**Comment by Sintinium** [comment]
Thanks for letting me know. I'll try to get it updated soon.

**Comment by Hubcapp** [comment]
Thanks for resolving, you're awesome. :-)
