### ISSUE TITLE
OAuth not launching browser on Mac

### ISSUE THREAD

**Issue by toolongtospell** [Sintinium/oauth#36]
Minecraft Version: 1.16.5
Forge Version: 36.2.23
OAuth Version: 1.1.13-1.16.jar - Released March 15th, 2022

1. Click on OAuth in the upper left corner.
2. Click on Add Account.
3. Recieve message "Loading... Check your browser" (has cancel button)
4. No pages load / open (No errors, just stays on the Check your browser page)

I'm not sure if this has something to do with insufficient system permissions for a java application to open a browser window.

**Comment by Sintinium** [comment]
Unfortunately I don't have access to a mac to test but I don't think this is fixable on my side. I'd imagine it's a permission issue like you said. Sorry!

**Comment by mazunki** [comment]
I'm on Linux, and I get the same error. I believe it is explained by this:

```log
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: java.lang.UnsupportedOperationException: The BROWSE action is not supported on the current platform!
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.desktop/java.awt.Desktop.browse(Desktop.java:531)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//com.sintinium.oauth.login.MicrosoftLogin.authorizeUser(MicrosoftLogin.java:177)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//com.sintinium.oauth.login.MicrosoftLogin.callIfNotCancelled(MicrosoftLogin.java:142)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//com.sintinium.oauth.login.MicrosoftLogin.login(MicrosoftLogin.java:68)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at RFB-Launch//com.sintinium.oauth.gui.LoginTypeScreen.lambda$null$2(LoginTypeScreen.java:50)
[13:00:54] [Thread-104/INFO] [STDERR]: [java.lang.Throwable$WrappedPrintStream:println:785]: 	at java.base/java.lang.Thread.run(Thread.java:1583)
```

I think it could be useful to have a fallback available to copy and paste the link ourselves for this.
