### ISSUE TITLE
Log in issue when attempting to authorize Microsoft account

### ISSUE THREAD

**Issue by Vehnim** [Sintinium/oauth#47]
[07/10/2022 11:56:40 AM] [Netty Client IO #15/INFO] Attempting connection with missing mods [audiodeath, betteradvancements, bhmenu, clienttweaks, controlling, ctgui, ctm, custommainmenu, discordsuite, justenoughpetroleum, modelloader, modnametooltip, moreoverlays, mousetweaks, neat, oauth, overpoweredarmorbar, packmodemenu, resourceloader, tipthescales, toastcontrol, vanillafix, wailaharvestability, nofog] at SERVER
[07/10/2022 12:00:46 PM] Failed to receive response from paste API
[07/10/2022 12:00:46 PM] java.io.IOException: Server returned HTTP response code: 502 for URL: https://paste.atlauncher.com/api/create
[07/10/2022 12:00:46 PM] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)
[07/10/2022 12:00:46 PM] 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)
[07/10/2022 12:00:46 PM] 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)
[07/10/2022 12:00:46 PM] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:75)
[07/10/2022 12:00:46 PM] 	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)
[07/10/2022 12:00:46 PM] 	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
[07/10/2022 12:00:46 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[07/10/2022 12:00:46 PM] 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[07/10/2022 12:00:46 PM] 	at java.base/java.lang.Thread.run(Unknown Source)
[07/10/2022 12:00:46 PM] java.io.IOException: Server returned HTTP response code: 502 for URL: https://paste.atlauncher.com/api/create

	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(Unknown Source)

	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(Unknown Source)

	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(Unknown Source)

	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:75)

	at com.atlauncher.thread.PasteUpload.call(PasteUpload.java:36)

	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)

	at java.base/java.lang.Thread.run(Unknown Source)

[07/10/2022 12:00:46 PM] Log failed to upload: <html><head><title>502 Bad Gateway</title></head><body bgcolor="white"><center><h1>502 Bad Gateway</h1></center><hr><center>nginx</center></body></html>
[07/10/2022 12:01:13 PM] Copied Log to clipboard

**Comment by Sintinium** [comment]
This looks to be an error for atlauncher. Please create a new issue with the full log file. Thanks!
